#!/bin/bash
set -e

# --output 用于本地生成和测试；不安装依赖，不修改系统配置。
OUTPUT=/etc/profile.d/ssh_hello.sh
INSTALL_DEPS=1
while [ "$#" -gt 0 ]; do
    case "$1" in
        --output)
            [ "$#" -ge 2 ] || { echo '--output 需要文件路径' >&2; exit 1; }
            OUTPUT=$2
            INSTALL_DEPS=0
            shift 2
            ;;
        --no-install-deps) INSTALL_DEPS=0; shift ;;
        -h|--help)
            echo '用法: bash ssh_info.sh [--output 文件路径] [--no-install-deps]'
            exit 0
            ;;
        *) printf '未知参数: %s\n' "$1" >&2; exit 1 ;;
    esac
done

if [ ! -d "$(dirname "$OUTPUT")" ] || [ ! -w "$(dirname "$OUTPUT")" ]; then
    printf '无法写入 %s，请使用 root 安装，或用 --output 指定可写路径。\n' "$OUTPUT" >&2
    exit 1
fi
if [ -L "$OUTPUT" ] || [ -d "$OUTPUT" ]; then
    printf '目标是符号链接或目录，请先检查: %s\n' "$OUTPUT" >&2
    exit 1
fi

if ! command -v figlet >/dev/null 2>&1 && [ "$INSTALL_DEPS" -eq 1 ]; then
    echo '正在尝试安装 figlet（仅安装阶段执行）...'
    if [ "$EUID" -ne 0 ]; then
        echo '当前非 root，跳过依赖安装，使用普通文本。'
    elif command -v apt-get >/dev/null 2>&1; then
        (apt-get update && apt-get install -y figlet) || echo 'figlet 安装失败，使用普通文本。'
    elif command -v dnf >/dev/null 2>&1; then
        dnf install -y figlet || echo 'figlet 安装失败，使用普通文本。'
    elif command -v yum >/dev/null 2>&1; then
        yum install -y figlet || echo 'figlet 安装失败，使用普通文本。'
    elif command -v pacman >/dev/null 2>&1; then
        pacman -S --noconfirm figlet || echo 'figlet 安装失败，使用普通文本。'
    fi
fi

DEFAULT_BANNER=$(hostname 2>/dev/null || printf 'Server')
echo '=================================================='
read -r -p "请输入要生成的艺术字文本 (默认: $DEFAULT_BANNER): " BANNER_TEXT || true
BANNER_TEXT=${BANNER_TEXT:-$DEFAULT_BANNER}
echo '请选择艺术字颜色: 1.红 2.绿 3.黄 4.蓝 5.紫 6.青 7.白'
read -r -p '请输入颜色编号 (默认: 5): ' COLOR_CHOICE || true
case "$COLOR_CHOICE" in
    1) COLOR_CODE=31;; 2) COLOR_CODE=32;; 3) COLOR_CODE=33;;
    4) COLOR_CODE=34;; 6) COLOR_CODE=36;; 7) COLOR_CODE=37;;
    *) COLOR_CODE=35;;
esac

ASCII_ART=$BANNER_TEXT
if command -v figlet >/dev/null 2>&1; then
    # 文本从 stdin 传入，避免以 - 开头的名称被当作选项。
    ASCII_ART=$(printf '%s\n' "$BANNER_TEXT" | figlet -f standard) || ASCII_ART=$BANNER_TEXT
fi
# 生成 POSIX shell 单引号字符串，Banner 中的 $()、引号和反引号不能变成代码。
QUOTED_ART=$(printf '%s' "$ASCII_ART" | sed "s/'/'\\\\''/g")

# 同目录临时文件 + 原子替换，生成失败不会删掉已有的欢迎页。
TEMP_OUTPUT=$(mktemp "${OUTPUT}.tmp.XXXXXX")
trap 'rm -f -- "$TEMP_OUTPUT"' EXIT
{
cat <<'PROFILE_HEAD'
# Generated by ssh_hello. This file is sourced by /etc/profile (POSIX sh).
case $- in
    *i*)
        if [ -n "${SSH_CONNECTION:-}" ] && [ -t 1 ]; then
        (
            # 不污染用户的变量、函数、位置参数、locale 或 shell 选项。
            set +e
            set +u
            LC_ALL=C
            export LC_ALL
PROFILE_HEAD
printf "            printf '%s' '%s'\n" "\n\033[${COLOR_CODE}m%s\033[0m\n\n" "$QUOTED_ART"
cat <<'PROFILE_BODY'
            # timeout 不存在/不支持时直接降级，绝不无保护地运行慢命令。
            bounded() {
                command -v timeout >/dev/null 2>&1 || return 125
                timeout -k 1 1 "$@" 2>/dev/null
            }
            show() { printf '        %s : %s\n' "$1" "${2:-无法获取}"; }

            HOST_NAME=未知
            [ ! -r /proc/sys/kernel/hostname ] || IFS= read -r HOST_NAME < /proc/sys/kernel/hostname
            show '主 机 名' "$HOST_NAME"
            show '登录时间' "$(date '+%Y-%m-%d %H:%M:%S' 2>/dev/null)"
            OS_NAME=$(awk '/^PRETTY_NAME=/{sub(/^[^=]*=/, ""); sub(/^["\047]/, ""); sub(/["\047]$/, ""); print; exit}' /etc/os-release 2>/dev/null)
            show '系统版本' "${OS_NAME:-未知} | $(uname -r 2>/dev/null) | $(uname -m 2>/dev/null)"

            # 直接读取 proc，避免 top/ps/free 的全进程扫描和输出格式差异。
            if [ -r /proc/stat ]; then
                CPU_START=$(awk '/^cpu /{for(i=2;i<=9;i++) t+=$i; printf "%.0f %.0f\n", t, $5+$6; exit}' /proc/stat)
                sleep 0.1
                CPU_USAGE=$(awk -v start="$CPU_START" '
                    /^cpu / {
                        split(start, s); for(i=2;i<=9;i++) t+=$i
                        delta=t-s[1]; idle=$5+$6-s[2]
                        if(delta>0 && idle>=0 && idle<=delta) printf "%.1f%% (100ms 采样)", 100*(delta-idle)/delta
                        else printf "暂无采样"
                        exit
                    }' /proc/stat)
                CPU_COUNT=$(awk '/^cpu[0-9]+ /{n++} END{print n+0}' /proc/stat)
                show 'CPU 信息' "${CPU_COUNT} 核处理器"
                show 'CPU 占用' "$CPU_USAGE"
            fi
            show '系统负载' "$(awk '{print $1, $2, $3, "(1/5/15min)"}' /proc/loadavg 2>/dev/null)"
            if [ -r /proc/meminfo ]; then
                awk '
                    {v[$1]=$2}
                    END {
                        a=v["MemAvailable:"]
                        if (!("MemAvailable:" in v)) a=v["MemFree:"]+v["Buffers:"]+v["Cached:"]
                        if(v["MemTotal:"]>0) printf "        可用内存 : %.1f%% %.1fM\n", a*100/v["MemTotal:"], a/1024
                        if(v["SwapTotal:"]>0) printf "        交换内存 : %.1f%% %.1fM/%.1fM\n", 100*(v["SwapTotal:"]-v["SwapFree:"])/v["SwapTotal:"], (v["SwapTotal:"]-v["SwapFree:"])/1024, v["SwapTotal:"]/1024
                        else print "        交换内存 : 未启用"
                    }' /proc/meminfo
            fi
            set -- /proc/[0-9]*
            if [ -d "$1" ]; then show '进 程 数' "$#"; fi
            show '运行时间' "$(awk '{printf "%d天 %d小时 %d分钟 %d秒", $1/86400, ($1%86400)/3600, ($1%3600)/60, $1%60}' /proc/uptime 2>/dev/null)"

            # SSH_CONNECTION 的第三项就是本次连接的服务器地址，适用于多网卡/IPv6。
            read -r CURRENT_IP CURRENT_PORT SERVER_IP SERVER_PORT <<SSH_ADDRESS
$SSH_CONNECTION
SSH_ADDRESS
            show '设备 IP ' "$SERVER_IP"
            show '本次 IP ' "$CURRENT_IP"

            if DISK_INFO=$(bounded df -Pk /); then
                DISK_DISPLAY=$(printf '%s\n' "$DISK_INFO" | awk 'NR==2 && $2>0 {
                    printf "%.1f%% %.1fM", $4*100/$2, $4/1024
                    if($4<=0) printf " 警告，存储空间已满！"
                }')
                show '可用存储' "$DISK_DISPLAY"
            else
                show '可用存储' '已跳过（超时或工具不可用）'
            fi
            if WHO_INFO=$(bounded who); then
                show '在线终端' "$(printf '%s\n' "$WHO_INFO" | awk '$2 ~ /^pts\//{n++} END{print n+0}')"
            else
                show '在线终端' '已跳过（超时或工具不可用）'
            fi

            LAST_INFO=''
            if [ -n "${USER:-}" ] && command -v last >/dev/null 2>&1; then
                # 直接执行有上限的查询；不再用一次全量 last 来探测参数。
                LAST_ROWS=$(bounded last -wFi -n 20 "$USER")
                LAST_STATUS=$?
                # 参数不支持才尝试旧写法；超时后不重试，更不退回无参数 last。
                if [ "$LAST_STATUS" -eq 1 ]; then
                    LAST_ROWS=$(bounded last -i -n 20 "$USER")
                    LAST_STATUS=$?
                fi
                if [ "$LAST_STATUS" -eq 0 ]; then
                    LAST_INFO=$(printf '%s\n' "$LAST_ROWS" | awk -v tty="${SSH_TTY#/dev/}" '
                        $2 ~ /^pts\// {
                            if(!skipped && (tty=="" || $2==tty)) {skipped=1; next}
                            print; exit
                        }')
                fi
            fi
            if [ -n "$LAST_INFO" ]; then
                show '上次 IP ' "$(printf '%s\n' "$LAST_INFO" | awk '{print $3}')"
                show '上次登录' "$(printf '%s\n' "$LAST_INFO" | awk '{for(i=4;i<=NF;i++) printf "%s%s", (i==4?"":" "), $i}')"
            else
                show '上次登录' '近期无可用记录（最多查询 20 条；也可能超时或不支持 last）'
            fi

            # 近期摘要不是完整审计：只数 Failed password，避免 PAM 重复计数。
            AUTH_ROWS=''
            AUTH_SCOPE=''
            AUTH_FROM_JOURNAL=0
            if command -v journalctl >/dev/null 2>&1; then
                if AUTH_ROWS=$(bounded journalctl --no-pager -q -o cat -n 1000 --since=-24h \
                    -u ssh.service -u sshd.service -u 'sshd@*.service'); then
                    AUTH_SCOPE='24h 内最近最多 1000 条可读 journal 记录'
                    AUTH_FROM_JOURNAL=1
                fi
            fi
            if [ -z "$AUTH_SCOPE" ]; then
                for LOG_FILE in /var/log/auth.log /var/log/secure; do
                    if [ -r "$LOG_FILE" ]; then
                        # tail 从文件尾读取，同时限制字节和行数；不遍历整个日志。
                        if AUTH_ROWS=$(bounded tail -c 262144 "$LOG_FILE"); then
                            AUTH_ROWS=$(printf '%s\n' "$AUTH_ROWS" | tail -n 1000)
                            AUTH_SCOPE='日志末尾最多 1000 行 / 256KiB，未按时间筛选'
                            break
                        fi
                    fi
                done
            fi
            if [ -n "$AUTH_SCOPE" ]; then
                FAILED_COUNT=$(printf '%s\n' "$AUTH_ROWS" | awk -v journal="$AUTH_FROM_JOURNAL" '
                    /Failed password for / && (journal || /sshd/) {n++} END{print n+0}')
                show '密码失败' "${FAILED_COUNT}（$AUTH_SCOPE；所有用户）"
            else
                show '密码失败' '无法统计（无可读日志、工具不可用或超时）'
            fi
            printf '\n'
            exit 0
        )
        fi
        ;;
esac
# 即使调用方启用 errexit，也不影响其登录。
true
PROFILE_BODY
} > "$TEMP_OUTPUT"

/bin/sh -n "$TEMP_OUTPUT"
chmod 644 "$TEMP_OUTPUT"
mv -f -- "$TEMP_OUTPUT" "$OUTPUT"
printf '已生成: %s\n' "$OUTPUT"
if [ "$OUTPUT" = /etc/profile.d/ssh_hello.sh ]; then
    echo '安装完成！请重新连接 SSH 查看效果。'
else
    echo '仅生成文件，可用 sh -n 检查；交互式 SSH 登录时 source 该文件可预览。'
fi
